name: Build AWS CCM Artifacts

on:
  repository_dispatch: {}
  schedule:
    - cron: "0 14 * * 1"
  push:
    branches:
      - master

# Clone my fork
# Add upstream remote
# Pull upstream
# If changes
#  docker build/publish
#  chart build/publish
#  update my fork

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clone fork and compare
      id: compare
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git clone https://$GH_ACCESS_TOKEN@github.com/jgreat/cloud-provider-aws.git fork
        cd ./fork
        git remote add upstream https://github.com/kubernetes/cloud-provider-aws.git
        git pull upstream master
        echo "::set-output name=ahead::$(git status --porcelain -b | grep ahead || true)"

    - name: Setup environment
      if: steps.compare.outputs.ahead != ''
      run: |
        cd ./fork
        COMMIT_DATE=$(git --no-pager log -1 --format=%cd --date=format:%Y%m%d.T%H%M%S)
        VERSION="0.0.0-$COMMIT_DATE"
        echo $VERSION
        echo "::set-env name=VERSION::$VERSION"
        cd ../
        mkdir -p build
        cp -R ./chart ./build
        sed -i "s/%VERSION%/$VERSION/g" ./build/chart/Chart.yaml
        curl -f -H 'Cache-Control: max-age=0,no-cache' "http://charts.jgreat.me/index.yaml" -o ./build/old-index.yaml

    - name: Build and publish image
      if: steps.compare.outputs.ahead != ''
      uses: elgohr/Publish-Docker-Github-Action@2.15
      with:
        name: jgreat/aws-cloud-controller-manager
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./fork
        buildoptions: --ulimit memlock=-1
        tags: ${{ env.VERSION }},latest

    - name: Package chart
      if: steps.compare.outputs.ahead != ''
      uses: WyriHaximus/github-action-helm3@master
      with:
        exec: helm package -d ./build/package ./build/chart

    - name: Create chart index
      if: steps.compare.outputs.ahead != ''
      uses: WyriHaximus/github-action-helm3@master
      with:
        exec: helm repo index --url http://charts.jgreat.me --merge ./build/old-index.yaml ./build/package

    - name: Configure AWS credentials
      if: steps.compare.outputs.ahead != ''
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to S3
      if: steps.compare.outputs.ahead != ''
      run: aws s3 sync ./build/package/ s3://$AWS_S3_BUCKET --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    - name: Update Fork
      if: steps.compare.outputs.ahead != ''
      run: |
        cd fork
        git config --local user.email "jgreat@jgreat.me"
        git config --local user.name "cloud-provider-aws-builder"
        git push
